Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "aamhamdiS" do |s|
    s.vm.hostname = "Server"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.network "forwarded_port", guest: 80, host: 8080

    s.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end

    # s.vm.provision "shell", path: "scripts/ssh.sh"
    s.vm.provision "shell", path: "scripts/k3s-server.sh"
    s.vm.provision "file", source: "./confs", destination: "/home/vagrant/confs"
    s.vm.provision "shell", inline: <<-SHELL

      apk update
      apk add docker docker-cli-compose
      rc-update add docker boot
      service docker start

      # Wait for Docker socket to be ready
      echo "Waiting for Docker daemon..."
      until docker info &>/dev/null; do
        echo "Waiting for Docker socket..."
        sleep 2
      done
      echo "Docker is ready!"

      docker images rm -f $(docker images -q) || true

       # Wait for k3s to be ready
      until kubectl get nodes &>/dev/null; do
        echo "Waiting for k3s..."
        sleep 5
      done
      
      
      # Build images using k3s's containerd
      echo "Building app images..."

      cd /home/vagrant/confs/app1
      docker build -t app1:aamhamdi .
      
      cd /home/vagrant/confs/app2
      docker build -t app2:aamhamdi .
      
      cd /home/vagrant/confs/app3
      docker build -t app3:aamhamdi .
      
      # Verify images exist
      echo "Images built:"
      docker images | grep aamhamdi

      docker save app1:aamhamdi | sudo k3s ctr images import -
      docker save app2:aamhamdi | sudo k3s ctr images import -
      docker save app3:aamhamdi | sudo k3s ctr images import -
      
      # Apply all manifests
      kubectl apply -f /home/vagrant/confs
      echo "Applications deployed successfully!"
  
    SHELL
  end


end