Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "aamhamdiS" do |s|
    s.vm.hostname = "aamhamdiS"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.network "forwarded_port", guest: 80, host: 8080

    s.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    s.vm.provision "shell", path: "scripts/k3s-server.sh"
    s.vm.provision "shell", inline: <<-SHELL

      apt update
      apt install -y docker.io docker-compose
      systemctl enable docker
      service docker start

      # Wait for Docker socket to be ready
      echo "Waiting for Docker daemon..."
      until docker info &>/dev/null; do
        echo "Waiting for Docker socket..."
        sleep 2
      done
      echo "Docker is ready!"

      docker images rm -f $(docker images -q) || true

       # Wait for k3s to be ready
      until kubectl get nodes &>/dev/null; do
        echo "Waiting for k3s..."
        sleep 5
      done
      
      
      # Build images using k3s's containerd
      echo "Building app images..."

      cd /vagrant/confs/app1
      docker build -t app1:aamhamdi .
      
      cd /vagrant/confs/app2
      docker build -t app2:aamhamdi .
      
      cd /vagrant/confs/app3
      docker build -t app3:aamhamdi .
      
      # Verify images exist
      echo "Images built:"
      docker images | grep aamhamdi

      docker save app1:aamhamdi | sudo k3s ctr images import -
      docker save app2:aamhamdi | sudo k3s ctr images import -
      docker save app3:aamhamdi | sudo k3s ctr images import -
      
      # Apply all manifests
      kubectl apply -f /vagrant/confs
      echo "Applications deployed successfully!"

    SHELL
  end


end