Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "generic/alpine318"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # -------- VM 1: aamhamdiS - Server --------
  config.vm.define "aamhamdiS" do |s|
    s.vm.hostname = "Server"
    s.vm.network "private_network", ip: "192.168.56.110"

    s.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end

    # Provision: setup SSH key
    s.vm.provision "shell", path: "scripts/ssh.sh"
    s.vm.provision "shell", path: "scripts/k3s-server.sh"
  end

  # -------- VM 2: aamhamdiSW - Worker --------
  config.vm.define "aamhamdiSW" do |sw|
    sw.vm.hostname = "ServerWorker"
    sw.vm.network "private_network", ip: "192.168.56.111"


    sw.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    # Provision: setup SSH key
    sw.vm.provision "shell", path: "scripts/ssh.sh"
    
    sw.vm.provision "shell", privileged: false, inline: <<-SHELL
      # Worker -> Server
      sshpass -p "vagrant" ssh-copy-id -f -o StrictHostKeyChecking=no vagrant@192.168.56.110 || true
      # Server -> Worker (run remotely via ssh)
      ssh -o StrictHostKeyChecking=no -i /home/vagrant/.ssh/id_rsa vagrant@192.168.56.110 \
          "sshpass -p 'vagrant' ssh-copy-id -f -o StrictHostKeyChecking=no vagrant@192.168.56.111" || true
    SHELL
    sw.vm.provision "shell", privileged: false, path: "scripts/k3s-agent.sh"

    # sw.vm.provision "shell", path: "scripts/k3s-agent.sh"
  end
end