Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "aamhamdiS" do |s|
    s.vm.hostname = "aamhamdiS"
    s.vm.network "private_network", ip: "192.168.56.110"

    s.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    s.vm.provision "shell", path: "scripts/k3s-server.sh"
  end

  config.vm.define "aamhamdiSW" do |sw|
    sw.vm.hostname = "aamhamdiSW"
    sw.vm.network "private_network", ip: "192.168.56.111"


    sw.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    sw.vm.provision "shell", path: "scripts/k3s-agent.sh"
  end
end